apiVersion: v1
kind: Namespace
metadata:
  name: labelgun
  annotations:
    iam.amazonaws.com/permitted: ".*"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: labelgun-serviceaccount
  namespace: labelgun

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: labelgun-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
      - update
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: labelgun-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: labelgun-clusterrole
subjects:
  - kind: ServiceAccount
    name: labelgun-serviceaccount
    namespace: labelgun
