---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: labelgun
  namespace: labelgun
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: labelgun
        namespace: labelgun
      annotations:
        iam.amazonaws.com/role: pam.uat.k8s.lendingworks.co.uk--labelgun
    spec:
      serviceAccount: labelgun-serviceaccount
      containers:
        - env:
            - name: AWS_REGION
              value: eu-west-1
            - name: LABELGUN_ERR_THRESHOLD
              value: INFO
            - name: LABELGUN_INTERVAL
              value: "360"
            - name: LABELGUN_LABEL_TAG_PREFIX
              value: k8s.io/custom-
            - name: LABELGUN_NO_SCHEDULE_TAG_PREFIX
              value: k8s.io/custom-no-schedule
            - name: LABELGUN_PREFER_NO_SCHEDULE_TAG_PREFIX
              value: k8s.io/custom-prefer-no-schedule
            - name: LABELGUN_NO_EXECUTE_TAG_PREFIX
              value: k8s.io/custom-no-execute
          image: "lendingworks/labelgun:latest"
          imagePullPolicy: Always
          name: labelgun
